name: Aggregate Mintlify Docs

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: aggregate-mintlify-docs
  cancel-in-progress: true

jobs:
  aggregate-docs:
    runs-on: ubuntu-latest
    name: Aggregate mintlify docs
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Run mintlify action
        uses: mintlify/mintlify-multirepo-action@6f81a15088568b052142c8987bde8a1c96d808c0
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          target-branch: docs
          subdirectory: ./docs
          repos: |
            - owner: modaic-ai
              repo: modaic
            - owner: modaic-ai
              repo: retrievers
