name: Aggregate Mintlify Docs

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: aggregate-mintlify-docs
  cancel-in-progress: true

jobs:
  aggregate-docs:
    runs-on: ubuntu-latest
    name: Aggregate mintlify docs
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Run mintlify action
        uses: TyTodd/multirepo-action@main
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          target-branch: docs
          repos: |
            - owner: modaic-ai
              repo: modaic
              subdirectory: ./docs
            - owner: modaic-ai
              repo: retrievers
              subdirectory: ./docs
